### PR TITLE
upload-legacy-ami: switch from small channel to big one

### PR DESCRIPTION
**Pull request by vcunat**
We'd like to slim the -small channels by avoiding these images.

### CODE REVIEW

**Comment by vcunat** [comment]
Huh, the CI actually attempts to upload &ndash; or rather downloads the images from Hydra/cache and gets stuck before uploading to AWS.

**Comment by arianvp** [comment]
Lemme have a look. Yes. The CI does a smoke test of the AMI

**Comment by arianvp** [comment]
Ah i see what is going on. I think there is some weird permission issue when someone that is not me opens a PR GitHub actions doesn't give access to the GitHub Actions variables.

**Comment by arianvp** [comment]
> Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork.

**Pull request closed without merging**
